import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/stories/Header";
import { getTranslations } from "next-intl/server";
import Image from 'next/image'
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const t = await getTranslations();
  const baseUrl = "https://menschki.org/"

  function createLink(path: string, key: string) {
    return {
      href: baseUrl + path,
      title: t(`header.${key}`)
    }
  }

  return (
    <html lang="de">
      <body>
        <Theme accentColor='ruby' className="min-h-screen flex flex-col">
          <NextIntlClientProvider>
            <Header homepageHref={baseUrl} links={[
              { href: "/", title: t("header.learningPlatform"), selected: true },
              createLink("ueber-menschki/", "about"),
              createLink("blog/", "blog"),
              createLink("ergebnisse/", "results"),
              createLink("publikationen/", "publications"),
              createLink("kontakt/", "contact")
            ]} />
            <figure className="-z-1 absolute">
              <Image src="/MenschKI-Hero-Texture.webp" alt="" width={1437} height={1370} />
            </figure>
            {children}
          </NextIntlClientProvider>
        </Theme>
      </body>
    </html>
  );
}
